services:
  dynamic-customer-segmentation:
    container_name: dynamic-customer-segmentation
    build: .
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - csv-ondisk:/app/csv
    depends_on:
      postgres:
        condition: service_healthy
      mock-user-db-microservice:
        condition: service_healthy
  
  mock-user-db-microservice:
    container_name: mock-user-db-microservice
    build: ./_mock-user-db-microservice/
    ports:
      - "4224:80"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1
      interval: 5s
      retries: 5
      timeout: 10s

  postgres:
    container_name: postgres
    image: postgres:13.11-bullseye
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 120
  
volumes:
  pg-data:
  csv-ondisk: