services:
  integration-test:
    container_name: integration-test
    build: 
      context: ../
      dockerfile: integration-test/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      usermicroservice:
        condition: service_healthy
  
  usermicroservice:
    container_name: usermicroservice
    build: 
      context: ../_mock-user-db-microservice/
      dockerfile: ./Dockerfile
    ports:
      - "80"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/health || exit 1
      interval: 5s
      retries: 5
      timeout: 10s

  postgres:
    container_name: test-postgres
    image: postgres:13.11-bullseye
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuserpassword
      - POSTGRES_DB=testdb
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 2s
      timeout: 10s
      retries: 120